In [1]:
import cv2
import numpy as np


image = cv2.imread('C:\\Users\\Zahid\\Desktop\\Deep Learning\\openCVtutorials\\input.jpg')


In [2]:

M = np.ones(image.shape , dtype = 'uint8') * 75
print(M)
#Creates a numpy array with ones of same size of the image of type integer

[[[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 ...

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]

 [[75 75 75]
  [75 75 75]
  [75 75 75]
  ...
  [75 75 75]
  [75 75 75]
  [75 75 75]]]


In [3]:
#When we add  to our color values of our image the brightness increases
#when we subtract the brightness decreases

bright_image = cv2.add(image , M)
dark_image = cv2.subtract(image , M)

cv2.imshow('Bright' , bright_image)
cv2.imshow('Dark' , dark_image)

cv2.waitKey()
cv2.destroyAllWindows()